name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run salt-lint
      uses: rjfd/salt-lint-action@master
      env:
        ACTION_STATES_DIR: states
